name: .NET Library pipeline

on:
  push:
   branches:
     - main
  workflow_call:
    inputs:
      dotnet-version:
        description: .NET SDK version
        required: false
        type: string
        default: '8.0.x'

      package-repository:
        description: GitHub repository to associate the package with
        required: true
        type: string

      configuration:
        description: Build configuration
        required: false
        type: string
        default: Release

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --configuration ${{ inputs.configuration }} --no-restore


  build-and-release:
    name: Build & Release
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          dotnet build \
            --configuration ${{ inputs.configuration }} \
            --no-restore

      - name: Pack
        run: |
          dotnet pack \
            --configuration ${{ inputs.configuration }} \
            --no-build \
            --output ./output \
            -p:RepositoryUrl=https://github.com/${{ inputs.package-repository }}

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./output/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --skip-duplicate